apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-minecraft-server
  labels:
    app: my-minecraft-server
spec:
  selector:
    matchLabels:
      app: my-minecraft-server
  serviceName: "my-minecraft-server"
  replicas: 1
  template:
    metadata:
      labels:
        app: my-minecraft-server
    spec:
      containers:
      - image: itzg/minecraft-server
        name: my-minecraft-server
        env:
        - name: EULA
          value: "TRUE"
        - name: TZ
          value: Asia/Tokyo
        - name: TYPE
          value: PAPER
        - name: DIFFICULTY
          value: peaceful
        - name: OPS
          value: topi_banana
        ports:
        - name: minecraft
          containerPort: 25565
        volumeMounts:
        - name: my-minecraft-server-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: my-minecraft-server-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: my-minecraft-server
  labels:
    app: my-minecraft-server
spec:
  ports:
  - name: minecraft
    nodePort: 30001
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: minecraft
  type: NodePort
