version: '3'
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TZ: Asia/Tokyo
      TYPE: PAPER
      DIFFICULTY: peaceful
      MEMORY: 8G
      OPS: topi_banana
    volumes:
      - mcData:/data
    tty: true
    stdin_open: true
    deploy:
      placement:
        constraints:
         - node.hostname == worker01
      resources:
        limits:
          memory: 8192M
    depends_on:
      - filebrowser
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - mcData:/srv
    depends_on:
      - tunnel
  tunnel:
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=$CF_TOKEN
    depends_on:
      - console
  console:
    image: ubuntu
    command: sleep infinity
    depends_on:
      - git
  git:
    image: bitnami/git
    working_dir: /repo
    command: |
      sh -c
      "git init &&
      git remote add origin https://github.com/topi-banana/Minecraft_on_Docker.git &&
      git fetch --all --prune
      git pull origin main"
    tty: true
    stdin_open: true
    volumes:
      - mcData:/repo

volumes:
  mcData:
