version: '3'
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TZ: Asia/Tokyo
      TYPE: PAPER
      DIFFICULTY: peaceful
      MEMORY: 2G
      OPS: topi_banana
    volumes:
      - mcData:/data
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          memory: 2.5G
    depends_on:
      - filebrowser
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - mcData:/srv
    depends_on:
      - tunnel
  tunnel:
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=$CF_TOKEN
    depends_on:
      - console
  console:
    image: ubuntu
    command: sleep infinity
    depends_on:
      - git
  git:
    image: bitnami/git
    working_dir: /repo
    command: |
      sh -c
      "git clone https://github.com/topi-banana/Minecraft_on_Docker /cloned &&
       mv /cloned/* /repo"
    tty: true
    stdin_open: true
    volumes:
      - mcData:/repo

volumes:
  mcData:
