version: '3'
services:
  app:
    image: nginx
  tunnel:
    #restart: always
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=$CF_TOKEN
  console:
    image: ubuntu
    command: bash &
