version: '3'
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TZ: Asia/Tokyo
      TYPE: PAPER
      DIFFICULTY: peaceful
      MEMORY: 2G
    ports:
      - 25565:25565
    volumes:
      - mcData:/data
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          memory: 2.5G
  tunnel:
    #restart: always
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=$CF_TOKEN
  git:
    image: bitnami/git
    working_dir: /repo
    command: git clone https://github.com/topi-banana/Minecraft_on_Docker /cloned && mv /cloned/* /repo
    tty: true
    stdin_open: true
    volumes:
      - mcData:/repo
  console:
    image: ubuntu
    command: sleep infinity
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - mcData:/srv

volumes:
  mcData:
