version: '3'
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TZ: Asia/Tokyo
      TYPE: PAPER
      DIFFICULTY: peaceful
      MEMORY: 8G
      OPS: 
    volumes:
      - mcData:/data
    tty: true
    stdin_open: true
    deploy:
      placement:
        constraints:
         - node.hostname == worker01
      resources:
        limits:
          memory: 8192M
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - mcData:/srv
    deploy:
      placement:
        constraints:
         - node.hostname == worker01
  tunnel:
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=$CF_TOKEN
  git:
    image: bitnami/git
    working_dir: /repo
    command: |
      sh -c
      "git config --global --add safe.directory /repo ;
      git init ;
      git remote add origin https://github.com/topi-banana/Minecraft_on_Docker.git ;
      git fetch --all --prune ;
      git pull origin main ;
      sleep infinity"
    tty: true
    stdin_open: true
    volumes:
      - mcData:/repo
    deploy:
      placement:
        constraints:
         - node.hostname == worker01

volumes:
  mcData:
